- name: Add carta ppa
  apt_repository:
    repo: ppa:snwh/ppa
    state: present

- name: Install theme packages
  apt:
    pkg: "{{item}}"
    state: installed
  with_items:
    - paper-icon-theme

