---

- name: set uid
  user:
    name: "{{user.username}}"
    uid: "{{user.uid}}"
- name: re-own files
  file:
    path: "/home/{{user.username}}"
    state: directory
    recursive: true
    owner: "{{user.username}}"

