- hosts: workstation
  become: yes
  tasks:
    - hostname:
        name: "{{ansible_hostname}}"
    - apt:
        pkg: "{{item}}"
        state: present
      with_items:
        - build-essential
        - wget
        - curl
        - tree
        - libsqlite3-dev
        - sqlite3
        - xclip
        - firefox
        - software-properties-common
    - import_role:
        name: dotfiles
    - import_role:
        name: vim
    - import_role:
        name: firewall
    - import_role:
        name: java
    - import_role:
        name: rbenv
      vars:
        rbenv_global_ruby_version: 2.5.1
        rbenv_ruby_versions:
          - 2.4.4
          - 2.5.1
    - import_role:
        name: cinnamon
      #    - import_role:
      #     name: theme
    - import_role:
        name: admin_user


