- hosts: development
  become: yes
  roles:
    - role: hostname
      hostname: "{{ansible_hostname}}"
      
    - role: user
      user_username: malakai
      user_uid: 1337
      user_public_keys: "{{public_keys}}" 
      user_private_keys: "{{private_keys}}"
      
    - role: packages
      packages_names:
        - vim
        - aptitude
        - build-essential
        - wget
        - curl
        - openssh-server
        - software-properties-common
        - tree
        
    - role: git
      git_user_realname: Bryan Hockey
      git_username: malakai
      git_editor: vi
      git_user_email: bhock@umich.edu
      
    - role: firewall
    
    - role: mail
      mail_hostname: "{{ansible_hostname}}"
      mail_email_domain: "@bryan.hockey"
      
    - role: rbenv
      rbenv_ruby_version: 2.3.0
      rbenv_ruby_versions:
        - 2.3.0
      
