- hosts: development
  become: yes
  roles:
    - role: hostname
      hostname: "{{ansible_hostname}}"
      
    - role: user
      user_username: "{{user.username}}"
      user_uid: "{{user.uid}}"
      user_public_keys: "{{user.public_keys}}" 
      user_private_keys: "{{user.private_keys}}"
      
    - role: packages
      packages_names:
        - vim
        - aptitude
        - build-essential
        - wget
        - curl
        - openssh-server
        - software-properties-common
        - tree
        
    - role: git
      git_user_realname: "{{user.realname}}"
      git_username: "{{git.username}}"
      git_editor: vi
      git_user_email: "{{git.email}}"
      
    - role: firewall
          
    - role: rbenv
      rbenv_ruby_version: 2.3.0
      rbenv_ruby_versions:
        - 2.3.0
      
