- hosts: workstation
  become: yes
  roles:
    - role: hostname
      hostname: "{{ansible_hostname}}"
      
    - role: packages
      packages_names:
        - vim
        - build-essential
        - wget
        - curl
        - openssh-server
        - software-properties-common
        - tree
        - sqlite3
        - libsqlite3-dev
        
    - role: git
      git_user_realname: "{{user.realname}}"
      git_username: "{{git.username}}"
      git_editor: vi
      git_user_email: "{{git.email}}"
      git_system_user: "{{user.username}}"
      
    - role: firewall
    
    - role: mattwillsher.sshd
      sshd_skip_defaults: False
      sshd_manage_service: True
      sshd_allow_reload: True
      sshd:
        Port: 22
        Protocol: 2
        UsePrivilegeSeparation: yes
        HostbasedAuthentication: no
        PermitRootLogin: no
        StrictMode: yes
        PermitEmptyPasswords: no
          
    - role: rbenv
      rbenv_global_ruby_version: 2.3.0
      rbenv_ruby_versions:
        - 2.3.0
        - 2.3.1
      
