- hosts: workstation
  become: yes
  tasks:
    - hostname: "{{ansible_hostname}}"
    - include_role: admin_user
    - apt:
        pkg: "{{item}}"
        state: present
      with_items:
        - build-essential
        - wget
        - curl
        - tree
        - libsqlite3-dev
        - sqlite3
        - xclip
        - firefox
        - software-properties-common
    - include_role: dotfiles
    - include_role: vim
    - include_role: firewall
    - include_role: java
    - include_role: rbenv
      vars:
        rbenv_gloabl_ruby_version: 2.5.1
        rbenv_ruby_versions:
          - 2.4.4
          - 2.5.1
    - include_role: cinnamon
      #    - include_role: theme


