- name: download dotfiles
  git:
    accept_hostkey: true
    repo: "{{dotfiles_git}}"
    dest: "/home/{{user.username}}/dotfiles"

- name: remove .git dir
  file:
    path: "/home/{{user.username}}/dotfiles/.git"
    state: absent

- name: cp out dotfiles
  copy:
    src: "/home/{{user.username}}/dotfiles/"
    dest: "/home/{{user.username}}/"

- name: remove dotfiles dir
  file:
    path: "/home/{{user.username}}/dotfiles"
    state: absent
