- name: install git
  apt:
    pkg: "{{item}}"
    state: installed
  with_items:
    - git
    - git-core
    - git-man
    
- name: Install the git config
  template:
    src: gitconfig.j2
    dest: /home/{{git_system_user}}/.gitconfig
    force: yes
    owner: "{{git_system_user}}"
    mode: "u=rw,g=r,o=r"
    
