- name: install git
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - git
    - git-core
    - git-man

- name: Install the git config
  template:
    src: gitconfig.j2
    dest: /home/{{git_username}}/.gitconfig
    force: yes
    owner: "{{git_username}}"
    mode: "u=rw,g=r,o=r"

