- name: lets get mail from root
  apt:
    name: exim4
    state: latest

- name: set the email address in /etc/aliases
  lineinfile:
    create: true
    dest: /etc/aliases
    line: "root: {{mail_address}}"
    state: present
    insertafter: EOF
