- name: Install the packages
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - vim
    - vim-nox
    - vim-gtk

- name: create vim bundle dir
  file:
    path: "/home/{{user.username}}/.vim/bundle"
    state: directory

- name: download vundle from git
  git:
    accept_hostkey: true
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/{{user.username}}/.vim/bundle/Vundle.vim"

- name: install vundle
  command: vim +PluginInstall +qall
